### ISSUE TITLE
Pin to ipfs-cluster as well

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-npm-registry-mirror#4]
It will be a great test for Cluster to get the npm modules pinned to it as registry.js.ipfs.io fetches them.

@hsanjuan can you help with this?

**Comment by hsanjuan** [comment]
Sure. We have a a http-under-libp2p API so this should just submit them there (with the right credentials). That should be possible with NodeJS, but I've been meaning to write a pubsub-subscriber tool that can do things like that (pin CIDs broadcasted on a pubsub channel).
