### ISSUE TITLE
registry.js.ipfs.io WebPage

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-npm-registry-mirror#5]
The current page is already fantastic!

<img width="997" alt="image" src="https://user-images.githubusercontent.com/1211152/48942588-fc3de080-ef17-11e8-8207-c78d2f26b376.png">

I would say that it would also be helpful to have stats:
- current size of npm
- current size of npm on IPFS
- list of pinned packages
- number of replicas found in the network (cronjob to repeat once a week)

**Comment by achingbrain** [comment]
@scout it would be good to have a separate container to handle this so it doesn’t add more load to the registry mirror workers - let’s factor this into our infra conversations next week

**Comment by andrew** [comment]
Could also hook up a basic package lookup page, like https://andrew.github.io/npm-ipfs/index.html#bignumber
